spring.application.name: readme-generator

spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-8b-instant

# GitHub API Configuration
github.api.token: ${GITHUB_API_TOKEN}

# GROQ Configuration
groq.api.key: ${GROQ_API_KEY}

# Logging Configuration
logging:
  level:
    com.cwa.readmegenerator: DEBUG
    org.springframework.web: INFO
