spring.application.name: readme-generator

# GitHub API Configuration
github.api.token: ${GITHUB_API_TOKEN}

# Logging Configuration
logging:
  level:
    com.cwa.readmegenerator: DEBUG
    org.springframework.web: INFO
